version: "3.8"
services:
    api:
        # image: stephan/user_server
        build:
            dockerfile: Dockerfile
            context: ./
        depends_on:
              - postgres  
        environment:
              POSTGRES_HOST : '127.0.0.1'
              POSTGRES_USER : postgres 
              POSTGRES_PASSWORD : amiramir16 
              POSTGRES_DB: nrich_db_2
              MODE_ENV : development
              PORT : 3000
        ports:
            - "8080:3000"     

    postgres:
        image: postgres:12.13
        ports:
            - "35000:5432"
        environment:
            POSTGRES_USERNAME : postgres
            POSTGRES_PASSWORD : amiramir16
            POSTGRES_NAME : nrich_db_2
                    
